language: node_js

node_js:
  - "10"

cache: yarn

before_deploy:
  - yarn build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: v2018
  local-dir: build
  target-branch: master
